import Head from 'next/head'
import Image from 'next/image'
import Banner from '../components/Banner'
import Header from '../components/Header'
import LargeCard from '../components/LargeCard'
import MediumCard from '../components/MediumCard'
import SmallCard from '../components/SmallCard'
import { httpAgentOptions } from '../next.config'
// import styles from '../styles/Home.module.css'

export default function Home({exploreData, cardData}) {
  return (
    <div className=''>
      <Head>
        <title>Airbnb 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* header */}
      <Header/> 

      {/* banner */}
      <Banner/>

      {/* main section */}

      <main className=' max-w-7xl mx-auto px-8 sm:px-16'>

        <section className='pt-6 '>
          <h2 className='text-3xl font-semibold pb-5'>
            Explore your area
          </h2>
        <div className='grid grid-cols-1 sm:grid-cols-2 
        lg:grid-cols-3 xl:grid-cols-4'>
        {
            exploreData?.map(item=> (
              <SmallCard
                img={item.img}
                location={item.location}
                distance={item.distance}
                key={''}
              />
            ))
          }
        </div>
          
        </section>

        <section>
          <h2 className='font-semibold text-3xl'>
            Live Anywhere!
          </h2>

          <div className='flex space-x-3 overflow-scroll scrollbar-hide p-4 mt-4'>
          {
            cardData?.map(item => (
              <MediumCard key={''}
                          img={item.img}
                          title={item.title} />
            ))
          }
          </div>

          
        </section>

        <LargeCard 
            img='https://links.papareact.com/4cj'
            title={'The Greatest Outdoors'}
            description='some more longer text'
            buttonText={'Live freely!'} />
      </main>

      
    </div>
  )
}

export async function getStaticProps() {

  const https = require('https')
 const exploreData = await fetch('https://links.papareact.com/pyp', 
{
  agent: new https.Agent({
    rejectUnauthorized: false,
  })
}).then(
  (res)=> res.json()
 )

 const cardData = await fetch('https://links.papareact.com/zp1',
 {
  agent: new https.Agent({
    rejectUnauthorized: false,
  })
}).then(
  (res)=> res.json()
 )
 return {
  props: {
    exploreData, cardData
  }
 }
 
}